### ISSUE TITLE
Unable to manually load local .xml file correctly when IRIS .xml epoch loads incorrectly

### ISSUE THREAD

**Issue by mpatrick5957** [LANL-Seismoacoustics/infrapy#17]
Hi @jwebster-LANL  and team,

This is a summary of the issue we noted during our meeting.

When using a .xml file to manually load in station data the IRIS xml data will not clear properly. It loads back into the station info section at the same time the local .xml file is loaded, creating two different versions of the array channels from different epochs.  This stops infraview from being able to run beamforming as there are now too many stations. The IRIS data redownloads every time the station data is cleared and loaded back in which can lead to multiple duplications of the data unable to be cleared entirely unless infraview is closed and reopened. Even though there seems to be a button to remove the unwanted stations manually, nothing happens when the 'x' button is clicked. 

<img width="595" alt="Screenshot 2023-07-13 at 10 27 04 AM" src="https://github.com/LANL-Seismoacoustics/infrapy/assets/122564865/fff1e472-d8c0-46bb-b170-d41a29ec00e5">

<img width="1556" alt="Screenshot 2023-07-13 at 10 27 24 AM" src="https://github.com/LANL-Seismoacoustics/infrapy/assets/122564865/9aeb5911-2f85-4cc6-aed8-654475e15df4">

The station locations downloaded from IRIS by infraview pull from a closed epoch in the .xml file. If this pathway could be updated, there would be no need for us to load our own files. If this is an IRIS issue though and not an infraview issue that can be solved by your team, we need a way to delete the IRIS station information and keep it from redownloading when we load the local .xml files.

Thanks for your help,
Makayla Patrick, UUSS

**Comment by jwebster-LANL** [comment]
hmm, right now I'm not able to download data from those stations.  Unfortunately the obspy FDSN methods don't give much (any?) information as far as download errors/problems.  I am able to get data from other stations so I'm pretty confident that infrapy's code is correct.

The problem where the multiple copies of the stations are loaded is an infraview bug and I'll work on it.  Could you send me an example xml file?  I don't know if I have any handy.

The problem where the station locations from IRIS are from a closed epoch is almost certainly a problem with IRIS's FDSN server.  That's pretty surprising though because the IRIS server has been around for a while and that should have been sorted out by now.  Maybe there is an issue with how the UU stations' metadata was entered?  I haven't done that personally so I don't know what's involved. 

I'm going to work on what I can from my end.  This all needs to be fixed.

**Comment by jwebster-LANL** [comment]
The lastest updates addresses this. It may have introduced different issues but currently the program will first check for channel codes, and if they are there, will use those locations.  If there are no channel codes (or lat/lons within them), then it will try to use the station lat/lons.  The channel codes in FDSN should have the correct epoch locations.

**Comment by jwebster-LANL** [comment]
Marking this as closed.  Dealing with inventories correctly will probably be a continuing effort.
